version: '3.9'

services:
    application:
        image: node:14
        working_dir: /workspace
        entrypoint: yarn run start:dev
        environment: 
            - POSTGRES_CONNECTION_STRING=postgres://talentumtuum:password@postgres:5432/quest
            - APPLICATION_HTTP_PORT=3000
        ports:
            - 3000:3000
        volumes:
            - ./:/workspace
            - modules:/workspace/node_modules
            - yarncache:/workspace/.yarn-cache
        networks: 
            - postgres

    yarn:
        image: node:14
        working_dir: /workspace
        volumes:
            - ./:/workspace
            - modules:/workspace/node_modules
            - yarncache:/workspace/.yarn-cache
        environment:
            - YARN_CACHE_FOLDER=/workspace/.yarn-cache
        entrypoint: yarn

    postgres:
        image: postgres:13.2-alpine
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
            - type: bind
              source: ./db
              target: /usr/db
        networks:
            - postgres

    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: talentumtuum@pm.me
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_CONFIG_SERVER_MODE: 'False'
        POSTGRES_USER: talentumtuum
        POSTGRES_PASSWORD: password
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - 5050:80
      networks:
        - postgres

networks:
    postgres:
        driver: bridge

volumes:
    modules:
    yarncache:
    postgres:
    pgadmin:
